### ISSUE TITLE
Suggestions for Chapter 5: Advanced Modelling

### ISSUE THREAD

**Issue by leonlan** [d-krupke/cpsat-primer#50]
- [x] Structure: It could be beneficial to rearrange the topics here: specifically, I suggest putting the Intervals section right after Tour constraints. Scheduling is one of the most used applications of OR-Tools, while automaton/reservoir constraints seem more niche to me.

- [ ] Question: There are a lot of different interval variable creation methods (fixed size, optional, etc.). Are they different from each other or is it just a simple interface? For instance, you can also pass constant values to the start/end/size arguments in `new_interval_var`. I would assume that preprocessing takes care of the redundancies but I'm not sure about that.

  > The new_optional_interval_var is the most expressive but also the most expensive, while the new_fixed_size_interval_var is the least expressive and the easiest to optimize.

- [ ] Content: In my opinion, it is a bit much to describe all types of intervals here. Only keeping variable-sized interval variables should be enough to explain the concept of interval variables, while the fixed-size types can be briefly mentioned in a line or two afterwards (and the reason when to use fixed-size intervals). (Note: My perspective mostly comes from OR-Tools' machine scheduling examples which don't use fixed-size intervals.)

**Comment by d-krupke** [comment]
Regarding the structure: True. It made sense while these sections where very short as they seemed completely lost at the end. With the current text (and maybe soon a more extensive example), it makes sense to push them further to the end.

**Comment by d-krupke** [comment]
Regarding the question: Actually, the restricted versions just enter constants into the generic version. However, one reason to keep them is that it can be very beneficial to explicitly use the most restricted versions as this makes it easier to directly see potential complexities in your model. My students have often created creatively bad models because they see a complex constraint and try to use it to its full expressiveness. So, this is less about teaching intervals and more about teaching this soft skill. I also like to start with the simpler versions, which already allow to do cool stuff and then go into how to suddenly do complex stuff like packing with rotations with them. Another soft skill I wanted to teach here is that one should not have a too narrow view on variables and constraints (like assuming intervals are always time), as this is another common issue students have had.

**Comment by d-krupke** [comment]
Regarding fixed-size intervals, they are actually quite useful in timetable scheduling, which is a common use case for CP-SAT, which is why I did an explicit example on them.

**Comment by leonlan** [comment]
Just a quick heads-up: tomorrow I'll take the afternoon to work on this and #49 :)

**Comment by leonlan** [comment]
I only addressed the first comment in #55. I agree with your comments related to using the simpler interface!
